### ISSUE TITLE
Frankie auto injects lots of style tags on the header

### ISSUE THREAD

**Issue by kmquan** [FrankieFinancial/onboarding-widget#23]
Hi, as our customer is using Frankie, we are trying to swap it with our current form.
Everything works well as intended, but I found out the script is injecting CSS into header, which overrides current CSS of our system.
Is it an intended implementation? Is there anyway to wrap the Frankie CSS that it would not affect current layout? Else, we have to write custom CSS to remove the effect caused.

![image](https://user-images.githubusercontent.com/21258478/95832893-1cbdf080-0d65-11eb-927e-76e644f0cf20.png)
![image](https://user-images.githubusercontent.com/21258478/95832989-3eb77300-0d65-11eb-9833-eb34c6ee458e.png)

Thank you in advanced.

**Comment by dburles** [comment]
We have also ran into this same issue.

**Comment by aaronchipper** [comment]
Thanks, we're looking into this and hope to address it ASAP.

**Comment by pedrotorchio** [comment]
Hey guys, the vast majority of the multiple style tags will still be there, as they are also injected by the Onfido UI, but are namespaced and shouldn't affect your elements. 
On our side a few of them were unintentional leaks created by non partial sass files that were compiled and included in the global scope. Those are being removed right now and should be fixed by tomorrow. 
All our styles are contained within the #ff-onboarding-widget selector.

To allow me to make sure the solution is complete and enough, could you share the specific styles that affected your elements? @kmquan @dburles 

Thanks for creating this github issue, @kmquan

**Comment by pedrotorchio** [comment]
We just released an update that hopefully should fix the issue for both of you. All styles are prefixed with the selector for the widget when they are produced by us, or by the selector of the third party element (onfido ui sdk). 
Let me know if you have any further issues.

**Comment by kmquan** [comment]
@aaronchipper @pedrotorchio In my case, the style normalized default HTML elements like **img, picture, h1, etc.**
I see that they have been removed today.

I am really appreciated your quick support.
