### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by BrutalCoding** [FrankieFinancial/onboarding-widget#9]
Hi, 

Just cloned the repo and ran the following in the project directory:
npm install
npm run start:demo

It starts the nodejs server, but as soon as I navigate to the URL (127.0.0.1:3000) it crashes (UnhandledPromiseRejectionWarning etc).

> frankie-self-onboarding-widget-documentation@1.0.0 start:demo /Users/{username}/Development/frankiefinancial-onboarding-widget
> cross-env NODE_ENV=demo node ./index.js

Example app listening on port 3000! Go to http://127.0.0.1:3000/
(node:91906) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:91906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:91906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pedrotorchio** [comment]
Hey Daniel, thanks for letting us know.
There was a leftover requirement on environment variables that shouldn't be there when running the demo script. That was fixed just now. Also since you tried it we updated the version of the widget with a few [changes and improvements](https://github.com/FrankieFinancial/onboarding-widget/pull/12), so please have a look.

Let me know how it goes alright?

Thanks again
Pedro

**Comment by Shrishb** [comment]
issue has been fixed
